repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.11.0
    hooks:
      - id: black-jupyter
        name: black-jupyter
        description:
          "Black code formatter with Jupyter notebook support"
        entry: black
        language: python
        minimum_pre_commit_version: '2.9.2'
        require_serial: true
        types_or: [python, pyi, jupyter]
        additional_dependencies: [".[jupyter]"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "a66e98d"
    hooks:
      - id: mypy
        name: mypy
        description: 'Static type checker for Python'
        entry: mypy
        language: python
        'types_or': [ python, pyi ]
        args: [
            "--config-file=./mypy.ini",
        ]
        require_serial: true
        additional_dependencies: ["numpy>=2.0", "pandas-stubs", "scipy-stubs", "matplotlib-stubs", "types-PyYAML"]
        minimum_pre_commit_version: '2.9.2'

  - repo: local
    hooks:
      - id: block-nonempty-env
        name: .env Blocker
        description: "Prevent committing non-empty .env files"
        entry: python ./hook_scripts/check_env.py
        language: system
        require_serial: true
        always_run: true
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:

      - id: end-of-file-fixer
        name: EoF Fixer
        description: "Ensure files end with a newline"
        entry: end-of-file-fixer

      - id: trailing-whitespace
        name: Trailing Whitespace Remover
        description: "Remove trailing whitespace"
        entry: trailing-whitespace-fixer
